### PR TITLE
Enable Auto Update

### PR DESCRIPTION
**Pull request by nitishkumar71**
Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>

Have built most of the part from the given [pull](https://github.com/alexellis/homebrew-alexellis/pull/1/files) request using default actions

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for the PR and for removing the third-party GH Actions.
How has this been tested? Can you link me to your repo where your files were updated?

**Comment by nitishkumar71** [comment]
Please check [master](https://github.com/nitishkumar71/homebrew-alexellis) branch in the same repo. You can check the action [run](https://github.com/nitishkumar71/homebrew-alexellis/runs/1619624443?check_suite_focus=true) too.

**Comment by nitishkumar71** [comment]
@alexellis

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
